name: Run Python Script

on: 
  workflow_dispatch:

env:
  password: ${{ secrets.password1}}
  phone: ${{ secrets.phone }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
  RECIPIENT_WAID: ${{ secrets.RECIPIENT_WAID}}
  PHONE_NUMBER_ID: ${{ secrets.PHONE_NUMBER_ID }}
  
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Run Python Script
        run: |
          pip install -r requirements.txt
          python -m pip install playwright
          playwright install-deps
          python bot.py

  





      
